### ISSUE TITLE
New outlook 

### ISSUE THREAD

**Issue by greyghost11** [james2mid/timetable-vcs#3]
hi i kno nothing about code. I used this last year and it worked fine but not working this year. I think its to do with a new outlook but im not sure. Could someone look into this pls ty.

**Comment by midzdotdev** [comment]
Closing because I doubt this works with the current timetable (I'm no longer a student at lboro), and I'm aware that others have made forks of my code to work with the current timetables.

I'm archiving this repo now, sorry I can't be of any help.
